import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.scss";
import { ThemeProvider } from "@/context";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  variable: "--font-poppins",
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: "Chapter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={poppins.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
